# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 橙子的blog
email: zpc987@sina.com
description: > # this means to ignore newlines until "baseurl:"
 欢迎来到橙子的博客，我会在这里记录一些学习和工作上的心得和笔记，期待与您分享 ^_^ 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  zpc987

# Build settings
markdown: kramdown
